#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlickrLiveWallpaper.Resource", IsApplication=true)]

namespace FlickrLiveWallpaper
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::FlickrLiveWallpaper.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::FlickrLiveWallpaper.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int list_of_image_sizes = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int list_of_scroll_options = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int list_of_users = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int list_of_users_values = 2130771971;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public const int ApplicationName = 2130903040;
			
			// aapt resource value: 0x7F030002
			public const int app_name = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int debug_messages = 2130903043;
			
			// aapt resource value: 0x7F030001
			public const int Hello = 2130903041;
			
			// aapt resource value: 0x7F030004
			public const int interval = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int use_wallpaper = 2130903045;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F040000
			public const int prefs = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int wallpaper = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
